# Generated by Django 3.0.5 on 2020-05-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='Programmer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_formset.Programmer'),
        ),
    ]
