# Generated by Django 3.0.5 on 2020-05-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset', '0002_language_programmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='programmer',
            options={'ordering': ['-name']},
        ),
    ]
