# Generated by Django 3.0.5 on 2020-05-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset', '0003_auto_20200508_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
    ]
