# Generated by Django 3.0.5 on 2020-05-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset', '0004_auto_20200508_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmer',
            options={},
        ),
        migrations.RemoveField(
            model_name='language',
            name='Programmer',
        ),
        migrations.AddField(
            model_name='language',
            name='isbn_number',
            field=models.CharField(default='', max_length=13),
        ),
    ]
