# Generated by Django 3.0.5 on 2020-05-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset', '0005_auto_20200508_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='isbn_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='language',
            table='book',
        ),
    ]
