# Generated by Django 3.0.5 on 2020-05-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset', '0006_auto_20200508_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='isbn_number',
        ),
        migrations.AddField(
            model_name='language',
            name='Programmer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='language',
            table=None,
        ),
    ]
