# Generated by Django 3.0.5 on 2020-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_app', '0003_auto_20200420_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, default='', upload_to='user_img'),
        ),
    ]
