# Generated by Django 3.0.5 on 2020-05-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_app', '0004_auto_20200501_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(default='', upload_to='user_img'),
        ),
    ]
