# Generated by Django 3.0.5 on 2020-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_app', '0005_auto_20200501_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(upload_to='user_img'),
        ),
    ]
